# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7b1a15514e877b4108db77b5f4333c7f947bf30f9013a4361c8357214d71e949ca9f66b7f487509433c04856c35107eb5e7bcf155e793809e95f4ad0ffbed8a

test:
  secret_key_base: 0bd99e33938507f9afbe4d792dc59ce8400b649f369b2ec6c0d0c3b01ab26bf53cde560616a3f08e946f7ef542d2d4b7a7f7ff2bae05f4a6e9be77b8bdd5e54e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
